In [1]:
import IM_rank_correlations as IMR

In [2]:
ranks_matrix = IMR.ranks(IMR.scores_matrix, IMR.measures_arr);

In [3]:
clusters  = ranks_matrix.form_clusters(2);
# ranks_matrix.remove_outliers(clusters[1]);
# clusters_single  = ranks_matrix.form_clusters(2, 'single');
# clusters_complete  = ranks_matrix.form_clusters(2, 'complete');

In [4]:
print(clusters)
# print(clusters_complete)

# ranks_matrix.show_dendrogram(linkage_method='single');
# ranks_matrix.show_dendrogram(linkage_method='average');
# ranks_matrix.show_dendrogram(linkage_method='complete');
# ranks_matrix.show_dendrogram(linkage_method='centroid');


[ array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 41, 42, 43, 44, 45, 46, 47, 48, 49])
 array([16, 17, 38, 39, 40])]


In [66]:
n_clusters = 10;
clusters = ranks_matrix.form_clusters(n_clusters);
print(clusters)

[array([ 0,  4,  5, 11, 15, 23])
 array([ 1,  2,  9, 12, 14, 24, 26, 32, 44, 45, 46, 47, 48, 49])
 array([ 3,  6, 10, 13, 18, 19, 20, 21, 22, 25, 28, 29, 30, 31, 33, 34, 35,
       36, 37, 42, 43])
 array([7, 8]) array([16]) array([17]) array([27, 41]) array([38])
 array([39]) array([40])]


In [67]:
import measure_classification as mc;
import compute_invariance;

In [68]:
measures_arr = ranks_matrix.measures_arr;
measures_dict = ranks_matrix.measures_dict;
property_dict = compute_invariance.compute_property_vectors(measures_dict);
X,Y = mc.initialize_X_Y(measures_arr, property_dict);

In [69]:
X = mc.form_X(property_dict, measures_dict, X);
Y = mc.assign_clusters_to_Y(clusters, Y);
X.shape

(50, 7)

In [70]:
# import numpy as np;
# measures_arr[(X[:,12] == 0) & (X[:,38] == 1) & (X[:,41] == 0)]

In [71]:
# ranks_matrix.show_dendrogram()

In [72]:
predictions, tree_classifier = mc.classify_decision_tree(X,Y, criterion='gini');
print(tree_classifier.score(X,Y))

0.7


In [73]:
mc.export_to_pdf(tree_classifier, n_clusters, len(measures_arr))

In [54]:
# from sklearn.manifold import t_sne;
# from sklearn.manifold import Isomap;
# n_components = 2;

# isomap = Isomap(n_components=n_components);
# tsne = t_sne.TSNE(n_components=n_components);

# # plot = isomap.fit_transform(X);
# plot = tsne.fit_transform(X);
# print(plot.shape)

# import matplotlib.pyplot as plt;
# import itertools;

# for i,j in itertools.combinations(range(n_components), 2):
#     plt.scatter(plot[:,i], plot[:,j], c = Y, cmap = plt.cm.Spectral);
#     plt.title(str(i) + ',' +str(j));
#     plt.show()



In [14]:
from sklearn.cluster import AgglomerativeClustering

In [55]:
agg_cluster = AgglomerativeClustering(n_clusters=7);

In [56]:
Y_prop = agg_cluster.fit_predict(X)
print(Y_prop)

[4 4 4 0 2 2 6 3 3 4 0 1 3 1 4 2 5 5 3 0 0 6 6 2 2 3 1 3 3 3 3 1 4 3 3 0 3
 1 5 0 1 3 0 3 4 3 3 0 3 3]


In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,Y_prop, random_state=43, train_size = 0.7)
predictions, tree_classifier = mc.classify_decision_tree(X,Y_prop, criterion='gini');
print(tree_classifier.score(X_test,y_test))

1.0


In [62]:
mc.export_to_pdf(tree_classifier, n_clusters, len(measures_arr))

In [63]:
measures_arr[(X[:,6] == 1) & (X[:,1] == 1)]

array(['jaccard', 'f_measure', 'kulczynsky_1', 'cosine',
       'least_contradiction'], 
      dtype='<U29')