In [1]:
import numpy as np

In [2]:
from Measures import map_measures_to_indices;

In [3]:
(measures_dict, measures_arr) = map_measures_to_indices();

In [4]:
from Contingency_Table import contingency_table, generate_contingency_tables;

In [5]:
vals = np.array([1,100,14,27]);

In [6]:
tables = generate_contingency_tables(vals);

In [7]:
n_measures = len(measures_dict);
n_scores = len(vals)**4;
scores_matrix = np.zeros(shape=(n_scores,n_measures));

In [8]:
# computes scores for each table and updates the scores matrix
for idx,table in enumerate(tables):
    t = contingency_table(table);
    t.compute_scores();
    scores_matrix[idx] = t.scores;

In [9]:
u, i, c = np.unique(scores_matrix[:,idx], return_counts=True, return_index=True);
# print(u, i, c, i.shape)

IndexError: index 255 is out of bounds for axis 1 with size 50

In [56]:
import itertools;
idx = measures_dict['confirm_descriptive'];
print(measures_arr[idx]);
invariances = [];
#unique vals, indices, counts
u, i, c = np.unique(scores_matrix[:,idx], return_counts=True, return_index=True)

for pos, index in enumerate(i):
    if (c[pos] >= 2):
#         print(index)
        t = tables[scores_matrix[:,idx] == scores_matrix[index,idx]];
        for i,j in itertools.combinations(range(len(t)),2):
            flag = 0;
            if check_null_invariance(t[i], t[j]):
                flag = 1;
                if not 'null' in invariances:
                    invariances.append('null');
#                 continue; #remove combinations with null invariance
#                 print(t[i], t[j]);

            if check_inversion_invariance(t[i], t[j]):
                flag = 1;
                if not 'inversion' in invariances:
                    invariances.append('inversion');
#                 continue; #remove combinations with inversion invariance
#                 print(t[i], t[j]);

            if check_ab_tweaking_invariance(t[i], t[j]):
                flag = 1;
                if not 'f11' in invariances:
                    invariances.append('f11');
#                 continue; #remove combinations with f11 tweaking invariance
#                 print(t[i], t[j]);

            if check_abprime_tweaking_invariance(t[i], t[j]):
                flag = 1;
                if not 'f10' in invariances:
                    invariances.append('f10');
#                 continue; #remove combinations with f10 tweaking invariance
#                 print(t[i], t[j]);

            if check_aprimeb_tweaking_invariance(t[i], t[j]):
                flag = 1;
                if not 'f01' in invariances:
                    invariances.append('f01');
#                 continue; #remove combinations with f10 tweaking invariance
#                 print(t[i], t[j]);

#             if check_P_bgivena_invariance(t[i], t[j]):
#                 flag = 1;
#                 if not 'p_b_given_a' in invariances:
#                     invariances.append('p_b_given_a');
# #                 continue; #remove combinations with P_given_a invariance
# #                 print(t[i], t[j]);

#             if check_P_agivenb_invariance(t[i], t[j]):
#                 flag = 1;
#                 if not 'p_a_given_b' in invariances:
#                     invariances.append('p_a_given_b');
# #                 continue; #remove combinations with P_given_a invariance
# #                 print(t[i], t[j]);

            if check_variable_permutation_invariance(t[i], t[j]):
                flag = 1;
                if not 'variable_permutation' in invariances:
                    invariances.append('variable_permutation');
#                 continue; #remove combinations with variable permutation
#                 print(t[i], t[j]);

            if check_off_diagonal_permutation_invariance(t[i], t[j]):
                flag = 1;
                if not 'off_diagonal_permutation' in invariances:
                    invariances.append('off_diagonal_permutation');
#                 print(t[i], t[j]);

#             # check null AND variable_permutation
            if check_null_AND_variable_permutation_invariance(t[i],t[j]):
                flag = 1;
                if not 'null_AND_variable_permutation' in invariances:
                    invariances.append('null_AND_variable_permutation');
#                 continue;
#                 print(t[i], t[j]);

            if check_column_permutation_invariance(t[i],t[j]):
                flag = 1;
                if not 'column_permutation' in invariances:
                    invariances.append('column_permutation');

            if check_row_permutation_invariance(t[i],t[j]):
                flag = 1;
                if not 'row_permutation' in invariances:
                    invariances.append('row_permutation');                    
                    
                    
            if check_row_scaling_invariance(t[i],t[j]):
                flag = 1;
                if not 'row_scaling' in invariances:
                    invariances.append('row_scaling');
                    
            if check_column_scaling_invariance(t[i],t[j]):
                flag = 1;
                if not 'column_scaling' in invariances:
                    invariances.append('column_scaling'); 
            
            if check_f11_f10_invariance(t[i],t[j]):
                flag = 1;
                if not 'f11_f10_invariance' in invariances:
                    invariances.append('f11_f10_invariance'); 
                    
            if not np.around(scores_matrix[index,idx],4):
                flag = 1;
            
            if not flag:
                pass;
                print(t[i], t[j], scores_matrix[index,idx]);

print(invariances)

confirm_descriptive
[  1.  14.  14.  27.] [ 14.  27.  14.   1.] -0.232142857143
[  1.  14.  27.  14.] [ 14.  27.   1.  14.] -0.232142857143
[  1.  14.  27.  27.] [ 14.  27.   1.  27.] -0.188405797101
[  1.  14.  27.  27.] [ 14.  27.  14.  14.] -0.188405797101
[  1.  14.  27.  27.] [ 14.  27.  27.   1.] -0.188405797101
[ 14.   1.  27.  27.] [ 27.  14.   1.  27.] 0.188405797101
[ 14.   1.  27.  27.] [ 27.  14.  14.  14.] 0.188405797101
[ 14.   1.  27.  27.] [ 27.  14.  27.   1.] 0.188405797101
[ 14.   1.  14.  27.] [ 27.  14.  14.   1.] 0.232142857143
[ 14.   1.  27.  14.] [ 27.  14.   1.  14.] 0.232142857143
['f11_f10_invariance', 'row_permutation', 'inversion', 'null', 'null_AND_variable_permutation', 'f01', 'row_scaling', 'column_scaling', 'column_permutation']


In [11]:
# measures_dict['mutual_information']
contingency_table([14,1,27,14]).least_contradiction()
contingency_table([27,14,14,100]).least_contradiction()

0.3170731707317073

In [12]:
def check_null_invariance(t1, t2):
    if (t1[0] == t2[0]) and (t1[1] == t2[1]) and (t1[2] == t2[2]):
        if not (t1[3] == t2[3]):
            return True;
    return False;

In [13]:
def check_inversion_invariance(t1, t2):
    if (t1[0] == t2[3]) and (t1[3] == t2[0]):
        if (t1[1] == t2[2]) and (t1[2] == t2[1]):
            return True;
    return False;

In [14]:
def check_off_diagonal_permutation_invariance(t1, t2):
    if (t1[0] == t2[3]) and (t1[3] == t2[0]):
        if (t1[1] == t2[1]) and (t1[2] == t2[2]):
            return True;
    return False;

In [15]:
def check_ab_tweaking_invariance(t1, t2):
    if (t1[1] == t2[1]) and (t1[2] == t2[2]) and (t1[3] == t2[3]):
        if not (t1[0] == t2[0]):
            return True;
    return False;

In [16]:
def check_abprime_tweaking_invariance(t1, t2):
    if (t1[0] == t2[0]) and (t1[2] == t2[2]) and (t1[3] == t2[3]):
        if not (t1[1] == t2[1]):
            return True;
    return False;

In [17]:
def check_aprimeb_tweaking_invariance(t1, t2):
    if (t1[0] == t2[0]) and (t1[1] == t2[1]) and (t1[3] == t2[3]):
        if not (t1[2] == t2[2]):
            return True;
    return False;

In [18]:
def check_variable_permutation_invariance(t1, t2):
    if (t1[0] == t2[0]) and (t1[3] == t2[3]):
        if (t1[1] == t2[2]) and (t1[2] == t2[1]):
            return True;
    return False;

In [19]:
def check_null_AND_variable_permutation_invariance(t1, t2):
    if (t1[0] == t2[0]):
        if (t1[1] == t2[2]) and (t1[2] == t2[1]):
            if not (t1[3] == t2[3]):
                return True;
    return False;

In [20]:
def check_P_bgivena_invariance(t1,t2):
    p1 = t1[0] / (t1[0] + t1[1]);
    p2 = t2[0] / (t2[0] + t2[1]);
    if (p1 == p2):
        return True;
    return False;

In [21]:
def check_P_agivenb_invariance(t1,t2):
    p1 = t1[0] / (t1[0] + t1[2]);
    p2 = t2[0] / (t2[0] + t2[2]);
    if (p1 == p2):
        return True;
    return False;    

In [22]:
def check_column_permutation_invariance(t1, t2):
    if (t1[0] == t2[1]) and (t1[1] == t2[0]) and (t1[2] == t2[3]) and (t1[3] == t2[2]):
            return True;
    return False;

In [23]:
def check_row_permutation_invariance(t1, t2):
    if (t1[0] == t2[2]) and (t1[1] == t2[3]) and (t1[2] == t2[0]) and (t1[3] == t2[1]):
            return True;
    return False;

In [24]:
def check_row_scaling_invariance(t1, t2):
    if ((t1[0]/t2[0]) == (t1[1]/t2[1])) and (t1[2]/t2[2]) == (t1[3]/t2[3]):
        return True;
    return False;

In [25]:
def check_column_scaling_invariance(t1, t2):
    if ((t1[0]/t2[0]) == (t1[2]/t2[2])) and (t1[1]/t2[1]) == (t1[3]/t2[3]):
        return True;
    return False;

In [55]:
def check_f11_f10_invariance(t1,t2):
    if (t1[0] == t2[0]) and (t1[1] == t2[1]):
        if not ((t1[2] == t2[2]) and (t1[3] == t2[3])):
            return True;
    return False

In [27]:
check_inversion_invariance([100,27,100,14], [14,100,27,100])

True

In [28]:
t1, t2 = tables[2], tables[3]

In [29]:
t2

array([  1.,   1.,   1.,  27.])

In [57]:
import scipy.misc as sm;
X = np.zeros(shape=(sm.comb(len(tables), 2),len(measures_arr)), dtype=int);
k = 0;

invariances = [];
for i in range(len(measures_arr)):
    invariances.append([]);
    
T_indices = np.zeros(sm.comb(len(tables),2), tuple)
for i,j in itertools.combinations(range(len(tables)),2):
# for i,j in itertools.combinations(range(30),2):
    T_indices[k] = (i,j);
    if not (i == j):
        for key,value in measures_dict.items():
            flag = 0;
            match = eval('contingency_table(tables[i]).'+ key +'() == contingency_table(tables[j]).' + key + '()');
            score = eval('contingency_table(tables[i]).'+ key +'()');
        
            # check if the scores are same
            if match:
                #check if null invariance was the reason:
                if check_null_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'null' in invariances[value]:
                        invariances[value].append('null')

                #check if inversion invariance was the reason:
                if check_inversion_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'inversion' in invariances[value]:
                        invariances[value].append('inversion');

                if check_variable_permutation_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'variable_permutation' in invariances[value]:
                        invariances[value].append('variable_permutation');
                        
                if check_off_diagonal_permutation_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'off_diagonal_permutation' in invariances[value]:
                        invariances[value].append('off_diagonal_permutation');

#                 if check_P_bgivena_invariance(tables[i], tables[j]):
#                     flag = 1;
#                     if not 'p_b_given_a' in invariances[value]:
#                         invariances[value].append('p_b_given_a');

#                 if check_P_agivenb_invariance(tables[i], tables[j]):
#                     flag = 1;
#                     if not 'p_a_given_b' in invariances[value]:
#                         invariances[value].append('p_a_given_b');
                        
                if check_null_AND_variable_permutation_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'null_variable_permutation' in invariances[value]:
                        invariances[value].append('null_variable_permutation');
                        
                if check_column_permutation_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'column_permutation' in invariances[value]:
                        invariances[value].append('column_permutation');
                        
                if check_row_permutation_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'row_permutation' in invariances[value]:
                        invariances[value].append('row_permutation');
                        
                if check_row_scaling_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'row_scaling' in invariances[value]:
                        invariances[value].append('row_scaling');
                        
                if check_column_scaling_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'column_scaling' in invariances[value]:
                        invariances[value].append('column_scaling');

                if check_f11_f10_invariance(tables[i], tables[j]):
                    flag = 1;
                    if not 'f11_f10_invariance' in invariances[value]:
                        invariances[value].append('f11_f10_invariance');

                #disregarding match when scores are zero
                if not np.around(score, 4):
                    flag = 1;
                        
                if not flag:
                    X[k,value] = eval('contingency_table(tables[i]).'+ key +'() == contingency_table(tables[j]).' + key + '()');
#                     print(measures_arr[value],score, i,j)
        k += 1;

/Users/abhisheksharma/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app
/Users/abhisheksharma/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:9: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [61]:
for i in range(10):
    print(T_indices[XRS_indices[i]])
# measures_arr[X[9,:]==1]

(174, 248)
(171, 242)
(14, 168)
(11, 162)
(1, 85)
(168, 254)
(1, 86)
(3, 254)
(87, 254)
(87, 253)


In [58]:
rows, columns = X.shape;
X_row_sum = np.zeros(rows, int);
for i in range(rows):
    X_row_sum[i] = np.sum(X[i,:]);

In [59]:
# [(measures_arr[i],np.sum(X[:,i])) for i in range(len(measures_arr))]

In [60]:
XRS_indices = (np.argsort(X_row_sum))[::-1];
(np.sort(X_row_sum))[::-1]

array([15, 15, 14, ...,  0,  0,  0])

In [63]:
tables[171], tables[242]

(array([ 14.,  14.,  14.,  27.]), array([ 27.,  27.,   1.,  14.]))

In [69]:
for i in range(len(measures_arr)):
    if not 'f11_f10_invariance' in invariances[i]:
        print(measures_arr[i])

leverage


In [ ]:
print(tables[15], tables[17])

In [65]:
invariances

[['null',
  'null_variable_permutation',
  'f11_f10_invariance',
  'column_scaling',
  'row_scaling',
  'row_permutation',
  'inversion',
  'column_permutation'],
 ['null',
  'null_variable_permutation',
  'f11_f10_invariance',
  'row_scaling',
  'column_scaling',
  'column_permutation',
  'inversion',
  'row_permutation'],
 ['null',
  'null_variable_permutation',
  'f11_f10_invariance',
  'row_scaling',
  'column_scaling',
  'column_permutation',
  'inversion',
  'row_permutation'],
 ['row_scaling',
  'f11_f10_invariance',
  'column_scaling',
  'inversion',
  'variable_permutation',
  'off_diagonal_permutation',
  'row_permutation',
  'column_permutation'],
 ['null',
  'null_variable_permutation',
  'f11_f10_invariance',
  'row_scaling',
  'column_scaling',
  'inversion',
  'variable_permutation'],
 ['null',
  'null_variable_permutation',
  'f11_f10_invariance',
  'row_scaling',
  'column_scaling',
  'inversion',
  'variable_permutation'],
 ['row_scaling',
  'f11_f10_invariance',
  'c

In [ ]:
# print(invariances[measures_dict['precision']])